
INSERT INTO `Taskrs` (`id`, `username`, `password`, `secQuestion1`, `secQuestionAnswer1`, `secQuestion2`, `secQuestionAnswer2`, `secQuestion3`, `secQuestionAnswer3`, `loggedIn`, `createdAt`, `updatedAt`)
VALUES
	(1,'duane','1234','Name of your childhood best friend?','ted','Name of your high school mascot?','ducks','Name of the street you grew up on?','main',1,'2018-03-15 06:55:06','2018-03-15 06:55:06'),
	(2,'keka','Keka','Name of your childhood best friend?','marie','Name of your first pet?','gucci','Apple or Samsung?','apple',1,'2018-03-15 06:55:51','2018-03-15 06:55:51'),
	(3,'gabe','Drak3','What is you mothers maiden name?','irma','Name of your first pet?','diamond','What is your favorite color?','brown',1,'2018-03-15 06:57:02','2018-03-15 07:01:24'),
	(4,'antoine','code123','Make of your first car?','jag','Name of your high school mascot?','hawks','Apple or Samsung?','samsung',1,'2018-03-15 06:59:14','2018-03-15 07:08:40');

INSERT INTO `tasks` (`id`,`title`,`price`,`category`,`body`,`dayofWeek`,`taskrName`,`taskrAccept`,`requesterAccept`,`taskrMarkComplete`,`requesterMarkComplete`,`taskeeId`,`taskeeName`,`taskPaid`,`taskComment`,`taskCommentTrue`,`createdAt`,`updatedAt`,`TaskrId`) VALUES (1,'Learn to ride a Bike',1000.00,'Instruction','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusce nec tellus sed augue semper po','Sunday','duane',0,0,0,0,NULL,NULL,NULL,NULL,0,'2018-03-19 00:40:06','2018-03-19 04:15:42',1);
INSERT INTO `tasks` (`id`,`title`,`price`,`category`,`body`,`dayofWeek`,`taskrName`,`taskrAccept`,`requesterAccept`,`taskrMarkComplete`,`requesterMarkComplete`,`taskeeId`,`taskeeName`,`taskPaid`,`taskComment`,`taskCommentTrue`,`createdAt`,`updatedAt`,`TaskrId`) VALUES (2,'Learn to Surf',50.00,'Instruction','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla ','Tuesday','duane',0,0,0,0,NULL,NULL,NULL,NULL,0,'2018-03-19 00:40:32','2018-03-19 00:40:32',1);
INSERT INTO `tasks` (`id`,`title`,`price`,`category`,`body`,`dayofWeek`,`taskrName`,`taskrAccept`,`requesterAccept`,`taskrMarkComplete`,`requesterMarkComplete`,`taskeeId`,`taskeeName`,`taskPaid`,`taskComment`,`taskCommentTrue`,`createdAt`,`updatedAt`,`TaskrId`) VALUES (3,'Mow your yard',25.00,'Home Maintenance',' I cut grass.','Thursday','duane',0,0,0,0,NULL,NULL,NULL,NULL,0,'2018-03-19 00:41:06','2018-03-19 00:41:06',1);
INSERT INTO `tasks` (`id`,`title`,`price`,`category`,`body`,`dayofWeek`,`taskrName`,`taskrAccept`,`requesterAccept`,`taskrMarkComplete`,`requesterMarkComplete`,`taskeeId`,`taskeeName`,`taskPaid`,`taskComment`,`taskCommentTrue`,`createdAt`,`updatedAt`,`TaskrId`) VALUES (4,'BarTender for Hire',35.00,'Culinary','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla ','Saturday','gabe',1,1,1,1,1,'duane',1,'Great Job Gabe!!!',1,'2018-03-19 00:43:00','2018-03-19 04:10:27',3);
INSERT INTO `tasks` (`id`,`title`,`price`,`category`,`body`,`dayofWeek`,`taskrName`,`taskrAccept`,`requesterAccept`,`taskrMarkComplete`,`requesterMarkComplete`,`taskeeId`,`taskeeName`,`taskPaid`,`taskComment`,`taskCommentTrue`,`createdAt`,`updatedAt`,`TaskrId`) VALUES (5,'Meal Prep',25.00,'Culinary','I will prep. Your meals for you','Monday','gabe',1,1,0,0,1,'duane',NULL,NULL,0,'2018-03-19 00:43:41','2018-03-19 05:37:22',3);
INSERT INTO `tasks` (`id`,`title`,`price`,`category`,`body`,`dayofWeek`,`taskrName`,`taskrAccept`,`requesterAccept`,`taskrMarkComplete`,`requesterMarkComplete`,`taskeeId`,`taskeeName`,`taskPaid`,`taskComment`,`taskCommentTrue`,`createdAt`,`updatedAt`,`TaskrId`) VALUES (6,'Learn to Code',15.00,'Instruction','Learn to code JavaScript and many other  Languagaes','Friday','gabe',0,0,0,0,0,'duane',NULL,NULL,0,'2018-03-19 00:44:26','2018-03-19 04:40:14',3);
INSERT INTO `tasks` (`id`,`title`,`price`,`category`,`body`,`dayofWeek`,`taskrName`,`taskrAccept`,`requesterAccept`,`taskrMarkComplete`,`requesterMarkComplete`,`taskeeId`,`taskeeName`,`taskPaid`,`taskComment`,`taskCommentTrue`,`createdAt`,`updatedAt`,`TaskrId`) VALUES (7,'Take you Shopping',100.00,'Instruction','I will remake your Closet','Sunday','keka',0,0,0,0,NULL,NULL,NULL,NULL,0,'2018-03-19 00:45:26','2018-03-19 00:45:26',2);
INSERT INTO `tasks` (`id`,`title`,`price`,`category`,`body`,`dayofWeek`,`taskrName`,`taskrAccept`,`requesterAccept`,`taskrMarkComplete`,`requesterMarkComplete`,`taskeeId`,`taskeeName`,`taskPaid`,`taskComment`,`taskCommentTrue`,`createdAt`,`updatedAt`,`TaskrId`) VALUES (8,'Dog Walking',40.00,'Childcare','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris.','Thursday','keka',0,0,0,0,NULL,NULL,NULL,NULL,0,'2018-03-19 00:46:04','2018-03-19 00:46:04',2);
INSERT INTO `tasks` (`id`,`title`,`price`,`category`,`body`,`dayofWeek`,`taskrName`,`taskrAccept`,`requesterAccept`,`taskrMarkComplete`,`requesterMarkComplete`,`taskeeId`,`taskeeName`,`taskPaid`,`taskComment`,`taskCommentTrue`,`createdAt`,`updatedAt`,`TaskrId`) VALUES (9,'Home Design Consult',500.00,'Instruction','Get  the home of your dreams','Thursday','keka',0,0,0,0,0,'duane',NULL,NULL,0,'2018-03-19 00:46:45','2018-03-19 04:40:49',2);
INSERT INTO `tasks` (`id`,`title`,`price`,`category`,`body`,`dayofWeek`,`taskrName`,`taskrAccept`,`requesterAccept`,`taskrMarkComplete`,`requesterMarkComplete`,`taskeeId`,`taskeeName`,`taskPaid`,`taskComment`,`taskCommentTrue`,`createdAt`,`updatedAt`,`TaskrId`) VALUES (10,'Car Detail',150.00,'Auto Maintenance','Get that car shinning like new','Saturday','antoine',0,0,0,0,NULL,NULL,NULL,NULL,0,'2018-03-19 00:47:43','2018-03-19 00:47:43',4);
INSERT INTO `tasks` (`id`,`title`,`price`,`category`,`body`,`dayofWeek`,`taskrName`,`taskrAccept`,`requesterAccept`,`taskrMarkComplete`,`requesterMarkComplete`,`taskeeId`,`taskeeName`,`taskPaid`,`taskComment`,`taskCommentTrue`,`createdAt`,`updatedAt`,`TaskrId`) VALUES (11,'Dinner prepared by Me',50.00,'Culinary','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. ','Sunday','antoine',0,0,0,0,0,'keka',NULL,NULL,0,'2018-03-19 00:48:24','2018-03-19 04:41:19',4);
INSERT INTO `tasks` (`id`,`title`,`price`,`category`,`body`,`dayofWeek`,`taskrName`,`taskrAccept`,`requesterAccept`,`taskrMarkComplete`,`requesterMarkComplete`,`taskeeId`,`taskeeName`,`taskPaid`,`taskComment`,`taskCommentTrue`,`createdAt`,`updatedAt`,`TaskrId`) VALUES (12,'Plan your next Event',25.00,'Event Planning','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. ','Sunday','antoine',0,0,0,0,NULL,NULL,NULL,NULL,0,'2018-03-19 00:49:15','2018-03-19 00:49:15',4);
